[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri                        = { workspace = true }
serde_json                   = { workspace = true }
core_lib                     = { workspace = true }
tauri-plugin-global-shortcut = { workspace = true }

[build-dependencies]
tauri-build = { workspace = true }